apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project-management-system-psi
  name: project-management-system-psi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-management-system-psi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project-management-system-psi
    spec:
      containers:
        - env:
            - name: PSI_SQL_SERVER
              valueFrom:
                configMapKeyRef:
                  key: PSI_SQL_SERVER
                  name: project-management-system-psi-config-hkcx
          image: >-
            gcr.io/stable-analogy-275618/github.com/avizen-j/project-management-system
          imagePullPolicy: IfNotPresent
          name: project-management-system-sha256-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: project-management-system-psi
  name: project-management-system-psi-service
  namespace: default
spec:
  clusterIP: 10.56.15.228
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32135
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: project-management-system-psi
  sessionAffinity: None
  type: LoadBalancer
